# Generated by Django 4.1.3 on 2022-11-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
