# Generated by Django 4.1.3 on 2022-11-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_contractor_rating_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
        ),
        migrations.AlterField(
            model_name='user',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
        ),
    ]
