# Generated by Django 4.1.3 on 2022-11-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_contractor_review_alter_user_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='review',
        ),
    ]
