# Generated by Django 4.1.3 on 2022-11-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_review_options_remove_review_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorphoto',
            name='user',
        ),
        migrations.AddField(
            model_name='contractorphoto',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.contractor'),
            preserve_default=False,
        ),
    ]
