# Generated by Django 4.1.3 on 2022-11-28 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_contractorphoto_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='posters',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.AddField(
            model_name='memberphoto',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member'),
        ),
    ]
