# Generated by Django 4.1.3 on 2022-11-29 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_memberphoto_remove_job_posters_rename_user_member_and_more'),
        ('main_app', '0014_alter_review_rating'),
    ]

    operations = [
    ]
