# Generated by Django 4.1.3 on 2022-11-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_job_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='member',
        ),
    ]
