# Generated by Django 4.1.3 on 2022-11-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_job_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.member'),
        ),
    ]
