# Generated by Django 4.1.3 on 2022-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_job_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="member",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.member",
            ),
        ),
    ]
