# Generated by Django 4.1.3 on 2022-11-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_remove_member_review_review_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
