# Generated by Django 4.1.3 on 2022-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0023_remove_review_review_review_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "⭐️"),
                    ("2", "⭐️⭐️"),
                    ("3", "⭐️⭐️⭐️"),
                    ("4", "⭐️⭐️⭐️⭐️"),
                    ("5", "⭐️⭐️⭐️⭐️⭐️"),
                ],
                max_length=1,
            ),
        ),
    ]
