# Generated by Django 4.1.3 on 2022-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='isDone',
            field=models.CharField(choices=[('1', 'Done'), ('2', 'Not Done')], default='2', max_length=1),
        ),
    ]
